apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zammad
  namespace: zammad
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: zammad
        component: services
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: zammad
          persistentVolumeClaim:
            claimName: zammad
        - name: nginx-configmap
          configMap:
             name: nginx-configmap
             items:
              - key: config
                path: default

      initContainers:
      - name: zammad-init
        image: b4rti/zammad-docker-compose:zammad
        args: [ "zammad-init" ]
        imagePullPolicy: Always
        volumeMounts:
         - name: zammad
           mountPath: /opt/zammad

      containers:
      - name: zammad-nginx
        image: b4rti/zammad-docker-compose:zammad
        args: [ "zammad-nginx" ]
        ports:
        - containerPort: 80
          name: nginx
        imagePullPolicy: Always
        volumeMounts:
         - name: zammad
           mountPath: /opt/zammad
         - name: nginx-configmap
           mountPath: /etc/nginx/sites-enabled
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10

      - name: zammad-railsserver
        image: b4rti/zammad-docker-compose:zammad
        args: ["zammad-railsserver"]
        imagePullPolicy: Always
        ports:
        - name: railsserver
          containerPort: 3000
        volumeMounts:
         - name: zammad
           mountPath: /opt/zammad
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 90
          periodSeconds: 10

      - name: zammad-scheduler
        image: b4rti/zammad-docker-compose:zammad
        args: [ "zammad-scheduler" ]
        imagePullPolicy: Always
        volumeMounts:
         - name: zammad
           mountPath: /opt/zammad

      - name: zammad-websocket
        image: b4rti/zammad-docker-compose:zammad
        args: [ "zammad-websocket" ]
        imagePullPolicy: Always
        ports:
        - name: websocket
          containerPort: 6042
        volumeMounts:
         - name: zammad
           mountPath: /opt/zammad
        readinessProbe:
          tcpSocket:
            port: 6042
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6042
          initialDelaySeconds: 60
          periodSeconds: 10
